"""slice0_learning_tasks_prompts_audit

Revision ID: f2f15dbd597f
Revises: fe56fa70289e
Create Date: 2026-09-27 13:46:02.695953

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f2f15dbd597f'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('admin_id', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('target_actor_id', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.CheckConstraint('char_length(result) > 0', name='ck_audit_result_not_empty'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('idx_audit_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('idx_audit_event', 'audit_logs', ['event'], unique=False)
    op.create_index('idx_audit_object', 'audit_logs', ['object_type', 'object_id'], unique=False)
    op.create_table('learning_tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_id', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('prompt_binding_id', sa.String(length=64), nullable=True),
    sa.Column('model_config_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('idx_learning_tasks_owner', 'learning_tasks', ['owner_user_id'], unique=False)
    op.create_index('idx_learning_tasks_status', 'learning_tasks', ['status'], unique=False)
    op.create_index('uq_learning_tasks_idem', 'learning_tasks', ['owner_user_id', 'idempotency_key'], unique=True)
    op.create_table('task_prompt_bindings',
    sa.Column('binding_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_name', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('langfuse_version', sa.String(length=64), nullable=True),
    sa.Column('template_snapshot', sa.Text(), nullable=False),
    sa.Column('template_sha256', sa.String(length=64), nullable=False),
    sa.Column('model_config_version', sa.String(length=64), nullable=True),
    sa.Column('output_schema_version', sa.String(length=40), nullable=True),
    sa.Column('tools_version', sa.String(length=40), nullable=True),
    sa.Column('agent_code_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('binding_id')
    )
    op.create_index(op.f('ix_task_prompt_bindings_task_id'), 'task_prompt_bindings', ['task_id'], unique=False)
    op.create_table('task_states',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_states_owner_user_id'), 'task_states', ['owner_user_id'], unique=False)
    op.create_table('task_attempts',
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('lease_token', sa.String(length=64), nullable=False),
    sa.Column('lease_owner', sa.String(length=64), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_status', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['learning_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index('idx_task_attempts_task', 'task_attempts', ['task_id'], unique=False)
    op.create_table('task_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('template_params', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task_states.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('task_id', 'sequence', name='uq_task_events_task_sequence')
    )
    op.create_index('idx_task_events_owner', 'task_events', ['owner_user_id'], unique=False)
    op.create_index('idx_task_events_task_seq', 'task_events', ['task_id', 'sequence'], unique=False)
    op.add_column('user', sa.Column('account_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False))
    op.add_column('user', sa.Column('failed_login_count', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locked_until')
    op.drop_column('user', 'failed_login_count')
    op.drop_column('user', 'account_status')
    op.drop_index('idx_task_events_task_seq', table_name='task_events')
    op.drop_index('idx_task_events_owner', table_name='task_events')
    op.drop_table('task_events')
    op.drop_index('idx_task_attempts_task', table_name='task_attempts')
    op.drop_table('task_attempts')
    op.drop_index(op.f('ix_task_states_owner_user_id'), table_name='task_states')
    op.drop_table('task_states')
    op.drop_index(op.f('ix_task_prompt_bindings_task_id'), table_name='task_prompt_bindings')
    op.drop_table('task_prompt_bindings')
    op.drop_index('uq_learning_tasks_idem', table_name='learning_tasks')
    op.drop_index('idx_learning_tasks_status', table_name='learning_tasks')
    op.drop_index('idx_learning_tasks_owner', table_name='learning_tasks')
    op.drop_table('learning_tasks')
    op.drop_index('idx_audit_object', table_name='audit_logs')
    op.drop_index('idx_audit_event', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
