"""task_events_audit_logs_foundation

Revision ID: 11fd41567866
Revises: 
Create Date: 2026-09-26 21:20:28.111871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11fd41567866'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('admin_id', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('target_actor_id', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.CheckConstraint('char_length(result) > 0', name='ck_audit_result_not_empty'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('idx_audit_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('idx_audit_event', 'audit_logs', ['event'], unique=False)
    op.create_index('idx_audit_object', 'audit_logs', ['object_type', 'object_id'], unique=False)
    op.create_table('task_states',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_states_owner_user_id'), 'task_states', ['owner_user_id'], unique=False)
    op.create_table('task_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('template_params', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task_states.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('task_id', 'sequence', name='uq_task_events_task_sequence')
    )
    op.create_index('idx_task_events_owner', 'task_events', ['owner_user_id'], unique=False)
    op.create_index('idx_task_events_task_seq', 'task_events', ['task_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_events_task_seq', table_name='task_events')
    op.drop_index('idx_task_events_owner', table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_task_states_owner_user_id'), table_name='task_states')
    op.drop_table('task_states')
    op.drop_index('idx_audit_object', table_name='audit_logs')
    op.drop_index('idx_audit_event', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
